### ISSUE TITLE
invalid error: "that token has been used already"

### ISSUE THREAD

**Issue by DallinYauney** [USUFSLC/usuprintcl#1]
I haven't used this service yet, but when it asks me to *verify my session*, the link it sends tells me that "that token has been used already" upon my first time clicking it.

It looks like it's not an issue with the outlook link verification system, as pasting the link directly gives the same issue.

**Comment by CodeTriangle** [comment]
I have just tried this, I get the same issue.

**Comment by emprespresso** [comment]
this happens because (i'm pretty sure at least) it's outlook's "link preview" feature. it visits the link somehow (i verified the source ip was coming from a microsoft owned subnet). aggieauth won't authenticate a token more than once so outlook is beating you to get to the token link by trying to make it "pretty".
looking for a fix.

**Comment by emprespresso** [comment]
should be fixed by https://github.com/USUFSLC/aggie-auth/commit/1661463b93fc0d05d4c516dfa15e0db06b5526eb

please confirm, and then close the issue if it works :)

**Comment by DallinYauney** [comment]
tragically, I'm still getting "that token has been used already" after clicking on the (very professional) redirect link.

**Comment by emprespresso** [comment]
okok try one last time. ive been completely in the dark because this is not reproducible for me.

**Comment by DallinYauney** [comment]
Still the same problem. Could be related to the fact that I'm using Outlook online, but I can't think of anything else that would cause this problem.

I can call you on discord some time if that'll help narrow down the issue

**Comment by emprespresso** [comment]
yeah im seeing it too in the logs. i have no idea what outlook is doing.

**Comment by emprespresso** [comment]
alright i've added a no follow tag on the anchor link in the email and a required checkbox to continue so outlook won't just keep following shit.
can you please check if that worked and report back? thanks again.

**Comment by DallinYauney** [comment]
it's a little clunky in the UI/UX, but it works!
